sensors:
  AM2302:
    type: AM2302
    pin: 4
  TSL2561:
    type: TSL2561
  Mic:
    type: Microphone
    device_name: hw:1,0
    file_type: wav
    format: S16_LE
    rate: 44100
  Cam:
    type: PiCamera

storage: ''
wifi:
  interface: "wlan0"

lift:
  ssid: 'LiftSystem 949f'
  psk: 'supersicher'
  hall_bottom: 5
  hall_top: 6

