sensors:
  RandomLow:
    type: Random
    maximum: 10
  RandomHigh:
    type: Random
    maximum: 100
  Files:
    type: RandomFile
  AM2302:
    type: AM2302
    pin: 23
  Mic:
    type: Microphone
    device_name: hw:1,0
    file_type: wav
    duration_sec: 10
    format: S16_LE
    rate: 44100
  Cam:
    type: Camera
storage: ''
